### ISSUE TITLE
First time hosting using Github-pages

### ISSUE THREAD

**Issue by osbornep** [sujaykundu777/devlopr-starter#1]
Hey, 

thank you for making this template, looks amazing!

Am having some issues setting up the template to be hosted through github pages. I have it working for a standard template and another custom one but cannot get this one working.

To keep this simple, I have the Gemfile with:

source 'https://rubygems.org'
gem "jekyll-remote-theme"

and _config.yml file with:

plugins:
  - jekyll-remote-theme
  
remote_theme: sujaykundu777/devlopr-starter

For a single main home link with the "page" layout as required to use custom jekyll themes. As mentioned I have this working for another custom theme but yours doesn't seem to show at all (page is just text without any formatting).

Is there something I have missed here?

Thanks
Phil

**Comment by jax79sg** [comment]
You got the theme wrong. It should be sujaykundu777/devlopr-jekyll

**Comment by osbornep** [comment]
Hi Jax, got it now thank you :)
