### ISSUE TITLE
TravisCI build error

### ISSUE THREAD

**Issue by MaiKuraki** [sujaykundu777/devlopr-starter#2]
Hi, thanks for your tutorials. I found some problem in the starter project. When I use Travis CI to build project with the file 'Gemfile.lock' included, It could make some error, like this

>$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
> /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (2.0.2) required by your /home/travis/build/MaiKuraki/maikuraki.github.io/Gemfile.lock. (Gem::GemNotFoundException)
> To update to the latest version installed on your system, run `bundle update --bundler`.
> To install the missing version, run `gem install bundler:2.0.2`
> 	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:303:in `activate_bin_path'
>	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `main'
> 
> The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 2 of 3.
> 
> /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (2.0.2) required by your /home/travis/build/MaiKuraki/maikuraki.github.io/Gemfile.lock. (Gem::GemNotFoundException)
> To update to the latest version installed on your system, run `bundle update --bundler`.
> To install the missing version, run `gem install bundler:2.0.2`
> 	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:303:in `activate_bin_path'
> 	from /home/travis/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `main'
> 
> The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 3 of 3.

to solve this problem, remove 'Gemfile.lock'.

**Comment by sujaykundu777** [comment]
Thanks mate. Its been resolved
